"""Shared rcParams plumbing for cinematic styles and user-defined brands.

A style is, at heart, a bundle of matplotlib rcParams. This module turns that
bundle into the four ways anyone would want to use it:

* a scoped context manager (``use``) that never leaks global state,
* a global ``apply`` / ``restore`` pair,
* registration as a named style sheet usable via ``plt.style.use(name)``,
* export to a ``matplotlibrc`` file for permanent, project-wide reuse.

Keeping the logic here lets the built-in film styles and
:class:`cinestyle.brand.Brand` share one tested implementation rather than
duplicating it.
"""

from __future__ import annotations

import contextlib
from collections.abc import Mapping
from pathlib import Path
from typing import Any, TypeVar

import matplotlib as mpl
import matplotlib.style as mstyle
from cycler import Cycler

T = TypeVar("T", bound="RcStyle")


def _strip_hash(color: str) -> str:
    """Return a color literal safe to write into a matplotlibrc file.

    ``#`` begins a comment in matplotlibrc files, so hex colors must be written
    without their leading hash; matplotlib's color validator re-adds it on read.
    Named colors and grayscale scalars pass through unchanged.
    """
    return color[1:] if color.startswith("#") else color


def _format_rc_value(value: Any) -> str:
    """Serialize a single rcParams value for a matplotlibrc file."""
    if isinstance(value, Cycler):
        colors = ", ".join(f"'{_strip_hash(str(e['color']))}'" for e in value)
        return f"cycler('color', [{colors}])"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, str):
        return _strip_hash(value)
    return str(value)


def register_style(name: str, rc: Mapping[str, Any]) -> str:
    """Register *rc* as a matplotlib style sheet named *name*.

    After this, ``matplotlib.pyplot.style.use(name)`` works anywhere in the
    process and *name* shows up in ``matplotlib.pyplot.style.available``.

    Args:
        name: Style-sheet name to register under.
        rc: The rcParams mapping to associate with the name.

    Returns:
        The registered name, for convenient chaining.
    """
    mstyle.library[name] = dict(rc)  # type: ignore[assignment]
    mstyle.available[:] = sorted(mstyle.library)
    return name


def write_matplotlibrc(rc: Mapping[str, Any], path: str | Path) -> Path:
    """Write *rc* to *path* as a matplotlibrc file and return the path.

    The result loads with ``plt.style.use(path)`` or can be dropped into a
    matplotlib ``stylelib`` directory for permanent reuse -- the "define a brand
    once and forget about it" workflow from the original branding notebook.
    """
    target = Path(path)
    lines = ["# Generated by cinestyle -- a reusable matplotlib brand.", ""]
    lines += [f"{key}: {_format_rc_value(value)}" for key, value in rc.items()]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


def read_matplotlibrc(path: str | Path) -> dict[str, Any]:
    """Parse a matplotlibrc file into a plain rcParams dict (file keys only)."""
    params = mpl.rc_params_from_file(str(path), use_default_template=False)
    return dict(params)


class RcStyle:
    """Mixin giving any object an ``as_rc()`` the four standard reuse modes.

    Subclasses only need to implement :meth:`as_rc`. Everything else -- scoped
    use, global apply/restore, style-sheet registration and matplotlibrc export
    -- is provided here and shared between the film styles and user brands.
    """

    name: str

    def as_rc(self) -> dict[str, Any]:
        """Return the rcParams mapping that defines this style."""
        raise NotImplementedError

    def use(self) -> contextlib.AbstractContextManager[None]:
        """Context manager that applies the style, then restores prior rcParams.

        This is the recommended entry point: styling is scoped to the ``with``
        block and global matplotlib state is left untouched afterwards.

        Example:
            >>> with FilmNoir().use():
            ...     fig, ax = plt.subplots()
            ...     ax.plot(x, y)
        """
        return mpl.rc_context(self.as_rc())

    @property
    def _snapshot(self) -> dict[str, Any]:
        snap = self.__dict__.get("_rc_snapshot")
        if snap is None:
            snap = {}
            self.__dict__["_rc_snapshot"] = snap
        return snap

    def save_defaults(self) -> None:
        """Record the current value of every rcParam this style will change."""
        snap = self._snapshot
        for key in self.as_rc():
            snap.setdefault(key, mpl.rcParams[key])

    def apply(self: T) -> T:
        """Apply the style to global rcParams, remembering the prior values.

        Prefer :meth:`use` unless you deliberately want process-wide styling;
        pair this with :meth:`restore` to undo it.
        """
        self.save_defaults()
        mpl.rcParams.update(self.as_rc())
        return self

    def restore(self) -> None:
        """Undo a previous :meth:`apply`, restoring the saved rcParams."""
        snap = self._snapshot
        if snap:
            mpl.rcParams.update(snap)
            snap.clear()

    def apply_style(self: T) -> T:
        """Backwards-compatible alias for :meth:`apply`."""
        return self.apply()

    def restore_defaults(self) -> None:
        """Backwards-compatible alias for :meth:`restore`."""
        self.restore()

    def register(self, name: str | None = None) -> str:
        """Register this style as a named matplotlib style sheet.

        Args:
            name: Override the default name (``cinestyle-<name>``).

        Returns:
            The registered style-sheet name.
        """
        return register_style(name or f"cinestyle-{self.name}", self.as_rc())

    def to_matplotlibrc(self, path: str | Path) -> Path:
        """Export this style to a matplotlibrc file for permanent reuse."""
        return write_matplotlibrc(self.as_rc(), path)
