"""The cinestyle theme catalog and film-look definitions.

Each :class:`~cinestyle.theme.Theme` is defined from a small set of sourced
"hero" colors; the categorical palette and colormaps are derived from them. Where
an authoritative, openly-licensed palette exists it is used verbatim (Wes
Anderson via the ``wesanderson`` R package; Ghibli via the ``ghibli`` R
package); the rest are sourced from documented color analyses and credited in
each theme's ``note``. Film titles are used descriptively for inspired-by
tributes and are trademarks of their respective owners; cinestyle is not
affiliated with or endorsed by any rights holder.
"""

from __future__ import annotations

from .luts import Look
from .theme import Theme

# --------------------------------------------------------------------- looks
# Original, hand-built grades (no third-party film-emulation LUTs redistributed).
LOOKS: dict[str, Look] = {
    "neon_night": Look(
        "neon_night",
        gamma=0.95,
        gain=1.05,
        saturation=1.25,
        shadow_tint="#0A0030",
        highlight_tint="#00E5FF",
        tint_strength=0.25,
    ),
    "teal_orange": Look(
        "teal_orange",
        saturation=1.15,
        shadow_tint="#0E4D64",
        highlight_tint="#E0531F",
        tint_strength=0.30,
    ),
    "warm_amber": Look(
        "warm_amber",
        gain=1.05,
        saturation=0.92,
        shadow_tint="#2C1A0A",
        highlight_tint="#F8C457",
        tint_strength=0.28,
    ),
    "noir_contrast": Look(
        "noir_contrast",
        gamma=0.85,
        saturation=0.15,
        shadow_tint="#000000",
        highlight_tint="#FFFFFF",
        tint_strength=0.10,
    ),
    "verdant": Look(
        "verdant",
        saturation=1.10,
        shadow_tint="#001100",
        highlight_tint="#00FF41",
        tint_strength=0.30,
    ),
    # neon_night blooms cyan; these two reach hues it cannot (Tron program-blue,
    # Drive's title magenta), so their themes get a look that tints the right way.
    "grid_glow": Look(
        "grid_glow",
        gamma=0.95,
        gain=1.05,
        saturation=1.20,
        shadow_tint="#03060C",
        highlight_tint="#6EE2FF",
        tint_strength=0.24,
    ),
    "scorpion": Look(
        "scorpion",
        gamma=0.97,
        gain=1.04,
        saturation=1.22,
        shadow_tint="#0A0710",
        highlight_tint="#EB1691",
        tint_strength=0.26,
    ),
    # The only *desaturating* look (saturation < 1): Nolan's sober cool grade,
    # where noir_contrast would crush to neutral black instead of cooling.
    "cold_steel": Look(
        "cold_steel",
        gamma=0.95,
        saturation=0.45,
        shadow_tint="#0B0F12",
        highlight_tint="#C7CDCE",
        tint_strength=0.22,
    ),
    # Red shadows, blue highlights: the inverse of teal_orange, for Argento's
    # good-vs-evil lighting.
    "giallo": Look(
        "giallo",
        gamma=0.95,
        gain=1.04,
        saturation=1.30,
        shadow_tint="#5B0000",
        highlight_tint="#0A36C4",
        tint_strength=0.30,
    ),
    "moonlit": Look(
        "moonlit",
        saturation=1.05,
        shadow_tint="#0C1626",
        highlight_tint="#E8B98A",
        tint_strength=0.24,
    ),
}


def get_look(name: str) -> Look:
    """Return the named film-look grade."""
    return LOOKS[name]


# -------------------------------------------------------------------- themes
_THEME_LIST: list[Theme] = [
    Theme(
        name="noir",
        heroes=("#FFFFFF", "#8B0000", "#9A9A9A", "#C0392B", "#5A5A5A"),
        cycle_length=5,
        background="#0A0A0A",
        surface="#141414",
        foreground="#F5F5F5",
        muted="#333333",
        grid=False,
        font_family="Oswald",
        seq_anchor="#8B0000",
        div_pair=("#1E6F8C", "#8B0000"),
        look="noir_contrast",
        film="Film noir / chiaroscuro (1940s-50s, neo-noir)",
        note="Chiaroscuro greyscale plus a blood-red accent; hex by construction.",
    ),
    Theme(
        name="ghibli",
        heroes=("#3C989B", "#7D9B5F", "#E3BBA1", "#F0A3B0", "#A3C5E0", "#D2CF39"),
        background="#FBF7EC",
        surface="#FBF7EC",
        foreground="#3A3A2E",
        muted="#D8D2C0",
        grid=True,
        font_family="EB Garamond",
        seq_anchor="#7D9B5F",
        div_pair=("#3C989B", "#E3BBA1"),
        film="Studio Ghibli (Hayao Miyazaki)",
        note="Derived from the ghibli R package (ewenme) / Movies in Color.",
    ),
    Theme(
        name="wes_anderson",
        heroes=("#F1BB7B", "#FD6467", "#5B1A18", "#D67236", "#3B9AB2", "#EBCC2A"),
        background="#F3E9D2",
        surface="#F3E9D2",
        foreground="#5B1A18",
        muted="#CBB99A",
        grid=False,
        framed=True,
        font_family="Jost",
        seq_anchor="#D67236",
        div_pair=("#3B9AB2", "#FD6467"),
        film="Wes Anderson (The Grand Budapest Hotel, The Life Aquatic)",
        note="Grand Budapest + Zissou, from the wesanderson R package (karthik).",
    ),
    Theme(
        name="blade_runner",
        heroes=("#08F7FE", "#FE53BB", "#F5D300", "#09FBD3", "#B537F2"),
        background="#05060A",
        surface="#0A0C12",
        foreground="#08F7FE",
        muted="#2E2150",
        grid=True,
        font_family="Orbitron",
        glow=0.7,
        seq_anchor="#08F7FE",
        div_pair=("#FE53BB", "#08F7FE"),
        look="neon_night",
        film="Blade Runner (1982), neon-noir / synthwave reading",
        note="Neon reading of the 1982 film; BR2049's grade is muted amber/teal.",
    ),
    Theme(
        name="star_wars",
        heroes=("#FFD700", "#1E90FF", "#C0392B", "#D2B48C", "#C0C0C0", "#4A6FA5"),
        cycle_length=6,
        background="#000000",
        surface="#0E0E12",
        foreground="#FFD700",
        muted="#2A2A33",
        grid=False,
        font_family="Oswald",
        title_weight="bold",
        seq_anchor="#FFD700",
        div_pair=("#1E90FF", "#C0392B"),
        film="Star Wars (original-trilogy-leaning)",
        note="Saber blue/Sith red, gold, Tatooine sand; hex by construction.",
    ),
    Theme(
        name="matrix",
        heroes=("#00FF41", "#03A062", "#008F11", "#003B00"),
        cycle_length=6,
        background="#0D0208",
        surface="#04120A",
        foreground="#00FF41",
        muted="#0A3315",
        grid=True,
        font_family="Share Tech Mono",
        glow=0.5,
        seq_anchor="#00FF41",
        film="The Matrix (Wachowskis)",
        note="Monochrome 'digital rain' green ramp; SchemeColor Matrix Code Green.",
    ),
    Theme(
        name="dune",
        heroes=("#E79B07", "#D5C0A1", "#6E6253", "#B07A43"),
        background="#EAD9BE",
        surface="#EAD9BE",
        foreground="#3A2C1C",
        muted="#C9B594",
        grid=True,
        font_family="Space Grotesk",
        seq_anchor="#E79B07",
        div_pair=("#0E4D64", "#E79B07"),
        look="warm_amber",
        film="Dune (Villeneuve, 2021)",
        note="Monochrome spice-amber / dune-sand; SchemeColor Dune + colorswall.",
    ),
    Theme(
        name="fury_road",
        heroes=("#E0531F", "#F2A900", "#0E4D64", "#1B6A8C"),
        cycle_length=6,
        background="#171210",
        surface="#211712",
        foreground="#F2A900",
        muted="#3A4A52",
        grid=False,
        font_family="Anton",
        seq_anchor="#E0531F",
        div_pair=("#0E4D64", "#E0531F"),
        look="teal_orange",
        film="Mad Max: Fury Road (colorist Eric Whipp)",
        note="Saturated teal-and-orange at the extreme; hex from documented intent.",
    ),
    Theme(
        name="kill_bill",
        heroes=("#FCD612", "#D61A1F", "#7A0A0A", "#E08A00"),
        cycle_length=5,
        background="#0A0A0A",
        surface="#161616",
        foreground="#FCD612",
        muted="#3A2A00",
        grid=False,
        font_family="Bebas Neue",
        seq_anchor="#FCD612",
        div_pair=("#FCD612", "#D61A1F"),
        film="Kill Bill (Tarantino)",
        note="Bride-yellow, black and blood-red; SchemeColor Kill Bill.",
    ),
    Theme(
        name="in_the_mood",
        heroes=("#CC0000", "#D58D29", "#F1C232", "#660000", "#2E5A4A"),
        background="#140A0A",
        surface="#1C1010",
        foreground="#F1C232",
        muted="#3A2420",
        grid=False,
        font_family="EB Garamond",
        seq_anchor="#CC0000",
        div_pair=("#2E5A4A", "#CC0000"),
        look="warm_amber",
        film="In the Mood for Love (Wong Kar-wai)",
        note="Smoldering reds/golds against cool green; color-hex 1061098.",
    ),
    Theme(
        name="sin_city",
        heroes=("#E4241C", "#F9DF28", "#97989A", "#7F7E7C", "#F6F5D7", "#000000"),
        cycle_length=5,
        background="#070707",
        surface="#121212",
        foreground="#EDEDED",
        muted="#2A2A2A",
        grid=False,
        font_family="Anton",
        seq_anchor="#E4241C",
        div_pair=("#F9DF28", "#E4241C"),
        look="noir_contrast",
        film="Sin City (Rodriguez/Miller, 2005)",
        note="B&W chiaroscuro plus red/yellow spot color; Movies In Color.",
    ),
    Theme(
        name="akira",
        heroes=("#EE272A", "#5D4E6D", "#9890A8"),
        cycle_length=6,
        background="#0B0610",
        surface="#140C18",
        foreground="#E6E2EC",
        muted="#2D2440",
        grid=True,
        font_family="Orbitron",
        glow=0.55,
        seq_anchor="#EE272A",
        div_pair=("#5D4E6D", "#EE272A"),
        look="neon_night",
        film="Akira (Otomo, 1988)",
        note="Kaneda red over cold Neo-Tokyo night; sampled from canonical stills.",
    ),
    Theme(
        name="the_fall",
        heroes=("#D3A201", "#D81B2B", "#1C4C8C", "#6F4B29"),
        cycle_length=6,
        background="#F1E2BE",
        surface="#EFDDB4",
        foreground="#3A2410",
        muted="#C9B488",
        grid=True,
        font_family="EB Garamond",
        seq_anchor="#C8951A",
        div_pair=("#1C4C8C", "#D81B2B"),
        look="warm_amber",
        film="The Fall (Tarsem, 2006)",
        note="Hyper-saturated jewel tones on parchment; from Movies In Color.",
    ),
    Theme(
        name="tron",
        heroes=("#6EE2FF", "#F7C530", "#F79D1E", "#FF410D", "#95CC5E", "#748AA6"),
        background="#05070A",
        surface="#0C1015",
        foreground="#D0DFE6",
        muted="#1E2A33",
        grid=True,
        font_family="Orbitron",
        glow=0.6,
        seq_anchor="#6EE2FF",
        div_pair=("#6EE2FF", "#F7C530"),
        look="grid_glow",
        film="Tron: Legacy (2010)",
        note="Program-blue vs CLU amber on the Grid; ggsci pal_tron('legacy'), GPL-3.",
    ),
    Theme(
        name="amelie",
        heroes=("#076D24", "#BB260D", "#F0BC15", "#47B748", "#71543B", "#A58168"),
        background="#140C06",
        surface="#1E140A",
        foreground="#F2D9A8",
        muted="#3A2A16",
        grid=False,
        font_family="EB Garamond",
        seq_anchor="#076D24",
        div_pair=("#076D24", "#BB260D"),
        look="warm_amber",
        film="Amelie (Jeunet, 2001)",
        note="Storybook green/red/gold, blue suppressed; color-hex 81484 cluster.",
    ),
    Theme(
        # Named for the film, not the director: this is the Shining palette
        # (Overlook carpet + cold blues), distinct from 2001's neon primaries.
        name="the_shining",
        heroes=("#DF5F18", "#981F24", "#7A3B12", "#1F3A5F", "#E8E2D0"),
        cycle_length=6,
        background="#0A0E14",
        surface="#12161E",
        foreground="#E8E2D0",
        muted="#243042",
        grid=False,
        font_family="Bebas Neue",
        seq_anchor="#DF5F18",
        div_pair=("#1F3A5F", "#DF5F18"),
        look="teal_orange",
        film="The Shining (Kubrick, 1980)",
        note="Hicks-carpet orange/red vs Overlook blue; minisvg recreation + analyses.",
    ),
    Theme(
        name="drive",
        heroes=("#EB1691", "#0493B2", "#F2C90E", "#F30812", "#F2F2F3"),
        cycle_length=6,
        background="#0A0710",
        surface="#120C18",
        foreground="#F2F2F3",
        muted="#241A2E",
        grid=True,
        font_family="Share Tech Mono",
        glow=0.55,
        seq_anchor="#EB1691",
        div_pair=("#0493B2", "#EB1691"),
        look="scorpion",
        film="Drive (Refn, 2011)",
        note="Scorpion magenta + LA-night teal + amber on black; color-hex 84839.",
    ),
    Theme(
        name="grand_budapest",
        heroes=("#E6A0C4", "#7294D4", "#D8A499", "#FD6467", "#5B1A18"),
        background="#F6ECDF",
        surface="#FBF4EA",
        foreground="#5B1A18",
        muted="#D9C7B0",
        grid=False,
        framed=True,
        font_family="Jost",
        seq_anchor="#E6A0C4",
        div_pair=("#7294D4", "#FD6467"),
        film="The Grand Budapest Hotel (Wes Anderson, 2014)",
        note="Mendl's pinks/lavenders; wesanderson GrandBudapest1+2 (karthik), MIT.",
    ),
    Theme(
        name="nolan",
        heroes=("#34505F", "#5E6B70", "#8A9499", "#C7CDCE"),
        cycle_length=6,
        background="#0B0F12",
        surface="#141B21",
        foreground="#C7CDCE",
        muted="#2A363E",
        grid=False,
        font_family="Space Grotesk",
        seq_anchor="#34505F",
        div_pair=("#8A9499", "#34505F"),
        look="cold_steel",
        film="Christopher Nolan house look (Interstellar, Inception, Dunkirk)",
        note="First muted theme: desaturated cool steel, cool-grey ramp by design.",
    ),
    Theme(
        name="hero",
        heroes=("#C1272D", "#1E4FA3", "#1F7A3D", "#E6B422", "#EDE7D2"),
        cycle_length=6,
        background="#0F0B06",
        surface="#171009",
        foreground="#EDE7D2",
        muted="#33291A",
        grid=False,
        font_family="Oswald",
        seq_anchor="#C1272D",
        div_pair=("#1E4FA3", "#C1272D"),
        film="Hero (Zhang Yimou, 2002)",
        note="Color-coded chapters (red/blue/green) over black; color-hex 62034.",
    ),
    Theme(
        name="suspiria",
        heroes=("#F20000", "#0A36C4", "#1FA84B", "#C81E78"),
        cycle_length=6,
        background="#0A0A0E",
        surface="#13121A",
        foreground="#EDE6E6",
        muted="#2C2B35",
        grid=True,
        font_family="Anton",
        glow=0.3,
        seq_anchor="#F20000",
        div_pair=("#0A36C4", "#F20000"),
        look="giallo",
        film="Suspiria (Argento, 1977)",
        note="Technicolor blood-red vs electric blue; color-hex 1036848 + derived.",
    ),
    Theme(
        name="moonlight",
        heroes=("#2A6F8E", "#3BA7A0", "#C8894E", "#E8B98A"),
        cycle_length=6,
        background="#0C1626",
        surface="#13202F",
        foreground="#DCE6EC",
        muted="#22384C",
        grid=True,
        font_family="Jost",
        glow=0.2,
        seq_anchor="#2A6F8E",
        div_pair=("#2A6F8E", "#C8894E"),
        look="moonlit",
        film="Moonlight (Barry Jenkins, 2016)",
        note="Miami-teal night with warm skin; from IndieWire colorist notes.",
    ),
    Theme(
        name="blade_runner_2049",
        heroes=("#027F93", "#F78B04", "#A30502", "#23AE9C"),
        cycle_length=6,
        background="#0A0E10",
        surface="#11171A",
        foreground="#DDE6E6",
        muted="#1C2D31",
        grid=True,
        font_family="Orbitron",
        glow=0.1,
        seq_anchor="#027F93",
        div_pair=("#027F93", "#F78B04"),
        look="teal_orange",
        film="Blade Runner 2049 (Villeneuve/Deakins, 2017)",
        note="Deakins' muted cyan/teal vs amber, not neon; color-hex 71647.",
    ),
    Theme(
        name="her",
        heroes=("#E8604C", "#C73E4C", "#E69B7B", "#D9A679"),
        cycle_length=6,
        background="#F6ECE0",
        surface="#FBF4EA",
        foreground="#5A3A36",
        muted="#E2CDB8",
        grid=True,
        font_family="EB Garamond",
        seq_anchor="#E8604C",
        div_pair=("#C73E4C", "#D9A679"),
        look="warm_amber",
        film="Her (Spike Jonze, 2013)",
        note="Warm corals and peach on cream, blue suppressed; colorist notes.",
    ),
]

THEMES: dict[str, Theme] = {theme.name: theme for theme in _THEME_LIST}


def get_theme(name: str) -> Theme:
    """Return a theme by name (e.g. ``"blade_runner"``)."""
    try:
        return THEMES[name]
    except KeyError:
        raise KeyError(
            f"Unknown theme {name!r}. Available: {', '.join(sorted(THEMES))}"
        ) from None


def list_themes() -> list[str]:
    """Return the names of all built-in themes, in catalog order."""
    return [theme.name for theme in _THEME_LIST]


def register(prefix: str = "cinestyle") -> list[str]:
    """Register every built-in theme as a named matplotlib style sheet.

    Also registers each theme's colormaps and named colors, so the styles are
    fully usable via ``plt.style.use(...)`` afterwards.

    Args:
        prefix: Style-sheet name prefix; themes register as ``<prefix>-<name>``.

    Returns:
        The registered style-sheet names.
    """
    return [theme.register(f"{prefix}-{theme.name}") for theme in _THEME_LIST]
